### PR TITLE
Added afd_total to the output metrics. 

### PR DESCRIPTION
**Pull request by villalonreina**
Just discussed with @RafaelNH about the best way to calculate the total AFD, which will be the sum of all the lobe's AFDs.

### CODE REVIEW

**Comment by CHrlS98** [comment]
@villalonreina Do you plan on adding anything else or it's ready to merge?

**Comment by villalonreina** [comment]
@CHrlS98 Actually not. I am pretty much done for now. You can go ahead and merge. Also, when should we meet @RafaelNH? What's left to be done?

**Comment by CHrlS98** [comment]
@villalonreina I'll try and fix the few points we discussed during our last meeting tomorrow. 
These are: 
* change default angle;
* investigate FD integral;
* and I'll address Serge's comments on the PR. 

Once this is done, we can coordinate something. Does that sound good?

**Comment by villalonreina** [comment]
@CHrlS98 Yes, that sounds great!

**Pull request merged**
